
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://mhd53.github.io"
## url: "mhd53.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Local Server settings
port: 8080

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Mohammad Darabi"
title: "mhd53"
description: "Blog and website of Mohammad Darabi, blogging mainly about personal projects."
keywords: "project, personal, mhd53"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg_03.jpeg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: False # Shuffle the lines false.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Life doesn't give you what you want."
  - text: "Life only gives you what you deserve."
##   - text: "The Gods will offer you chances."
##   - text: "Know them! Take them!"
##   - text: "The Gods are waiting to delight."

me-img: "/img/me2_01.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/machine_learning.svg.png"
    date: "July 2017 - December 2017"
    description: "Learning Machine Learning"
  - image: "/img/timeline/Android_Studio_icon.svg.png"
    date: "November 2016 - Today"
    description: "Android Development"
  - image: "/img/timeline/UnityLogo2.png"
    date: "January 2015 - Today"
    description: "Unity 3D Development"
  - image: "/img/timeline/timeline1_01.jpeg"
    date: "Aguest 2014 - Today"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/python-logo.svg.png"

###########
# Contact #
###########

email: "your@email.here"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: ""
author_blurb_image: ""

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/mhd53"
  - title: "facebook"
    url: "https://facebook.com/mohammad.darabi.53"
  - title: "instagram"
    url: "https://www.instagram.com/m.darabi53/"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username:
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  ## Blog: 'latest-post'
  Timeline: 'timeline'
  Projects: 'projects'
  ## Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jemoji
  - jekyll-paginate
